// This file is generated by scripts/update_iana_registry.py sync.
// Do not edit it by hand; see data/iana/README.md for the update workflow.
//
// IPv4 source: https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xml
// IPv4 source updated: 2025-10-09
// IPv4 source SHA-256: cf24e11f41b7d42c68debe2d18b97cac815084ec413ebb3b244f704028a16f20
// IPv6 source: https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xml
// IPv6 source updated: 2025-10-09
// IPv6 source SHA-256: c17f4380ba84fb2160dae82ebfd8bd155a5853cfab624ed3a9fd251638a8be02
//
// Snapshot rows: IPv4 25; IPv6 25. Aggregate prefixes: IPv4 26; IPv6 25.
// Canonical forwarding blacklist prefixes: IPv4 14; IPv6 139.

use core::net::{Ipv4Addr, Ipv6Addr};

use ipnet::{IpNet, Ipv4Net, Ipv6Net};

const RFC6890_IPV4_001: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(0, 0, 0, 0), 8);
const RFC6890_IPV4_002: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(0, 0, 0, 0), 32);
const RFC6890_IPV4_003: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(10, 0, 0, 0), 8);
const RFC6890_IPV4_004: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(100, 64, 0, 0), 10);
const RFC6890_IPV4_005: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(127, 0, 0, 0), 8);
const RFC6890_IPV4_006: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(169, 254, 0, 0), 16);
const RFC6890_IPV4_007: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(172, 16, 0, 0), 12);
const RFC6890_IPV4_008: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(192, 0, 0, 0), 24);
const RFC6890_IPV4_009: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(192, 0, 0, 0), 29);
const RFC6890_IPV4_010: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(192, 0, 0, 8), 32);
const RFC6890_IPV4_011: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(192, 0, 0, 9), 32);
const RFC6890_IPV4_012: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(192, 0, 0, 10), 32);
const RFC6890_IPV4_013: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(192, 0, 0, 170), 32);
const RFC6890_IPV4_014: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(192, 0, 0, 171), 32);
const RFC6890_IPV4_015: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(192, 0, 2, 0), 24);
const RFC6890_IPV4_016: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(192, 31, 196, 0), 24);
const RFC6890_IPV4_017: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(192, 52, 193, 0), 24);
const RFC6890_IPV4_018: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(192, 88, 99, 0), 24);
const RFC6890_IPV4_019: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(192, 88, 99, 2), 32);
const RFC6890_IPV4_020: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(192, 168, 0, 0), 16);
const RFC6890_IPV4_021: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(192, 175, 48, 0), 24);
const RFC6890_IPV4_022: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(198, 18, 0, 0), 15);
const RFC6890_IPV4_023: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(198, 51, 100, 0), 24);
const RFC6890_IPV4_024: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(203, 0, 113, 0), 24);
const RFC6890_IPV4_025: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(240, 0, 0, 0), 4);
const RFC6890_IPV4_026: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(255, 255, 255, 255), 32);

const RFC6890_IPV6_001: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0001,
  ),
  128,
);
const RFC6890_IPV6_002: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  128,
);
const RFC6890_IPV6_003: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0xffff, 0x0000, 0x0000,
  ),
  96,
);
const RFC6890_IPV6_004: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x0064, 0xff9b, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  96,
);
const RFC6890_IPV6_005: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x0064, 0xff9b, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  48,
);
const RFC6890_IPV6_006: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x0100, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  64,
);
const RFC6890_IPV6_007: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x0100, 0x0000, 0x0000, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  64,
);
const RFC6890_IPV6_008: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  23,
);
const RFC6890_IPV6_009: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  32,
);
const RFC6890_IPV6_010: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0001,
  ),
  128,
);
const RFC6890_IPV6_011: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0002,
  ),
  128,
);
const RFC6890_IPV6_012: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0003,
  ),
  128,
);
const RFC6890_IPV6_013: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  48,
);
const RFC6890_IPV6_014: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0003, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  32,
);
const RFC6890_IPV6_015: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0004, 0x0112, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  48,
);
const RFC6890_IPV6_016: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0010, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  28,
);
const RFC6890_IPV6_017: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0020, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  28,
);
const RFC6890_IPV6_018: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0030, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  28,
);
const RFC6890_IPV6_019: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0db8, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  32,
);
const RFC6890_IPV6_020: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2002, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  16,
);
const RFC6890_IPV6_021: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2620, 0x004f, 0x8000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  48,
);
const RFC6890_IPV6_022: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x3fff, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  20,
);
const RFC6890_IPV6_023: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x5f00, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  16,
);
const RFC6890_IPV6_024: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0xfc00, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  7,
);
const RFC6890_IPV6_025: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0xfe80, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  10,
);

const FORWARDING_BLACKLIST_IPV4_001: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(0, 0, 0, 0), 8);
const FORWARDING_BLACKLIST_IPV4_002: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(127, 0, 0, 0), 8);
const FORWARDING_BLACKLIST_IPV4_003: Ipv4Net =
  Ipv4Net::new_assert(Ipv4Addr::new(169, 254, 0, 0), 16);
const FORWARDING_BLACKLIST_IPV4_004: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(192, 0, 0, 8), 32);
const FORWARDING_BLACKLIST_IPV4_005: Ipv4Net =
  Ipv4Net::new_assert(Ipv4Addr::new(192, 0, 0, 11), 32);
const FORWARDING_BLACKLIST_IPV4_006: Ipv4Net =
  Ipv4Net::new_assert(Ipv4Addr::new(192, 0, 0, 12), 30);
const FORWARDING_BLACKLIST_IPV4_007: Ipv4Net =
  Ipv4Net::new_assert(Ipv4Addr::new(192, 0, 0, 16), 28);
const FORWARDING_BLACKLIST_IPV4_008: Ipv4Net =
  Ipv4Net::new_assert(Ipv4Addr::new(192, 0, 0, 32), 27);
const FORWARDING_BLACKLIST_IPV4_009: Ipv4Net =
  Ipv4Net::new_assert(Ipv4Addr::new(192, 0, 0, 64), 26);
const FORWARDING_BLACKLIST_IPV4_010: Ipv4Net =
  Ipv4Net::new_assert(Ipv4Addr::new(192, 0, 0, 128), 25);
const FORWARDING_BLACKLIST_IPV4_011: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(192, 0, 2, 0), 24);
const FORWARDING_BLACKLIST_IPV4_012: Ipv4Net =
  Ipv4Net::new_assert(Ipv4Addr::new(198, 51, 100, 0), 24);
const FORWARDING_BLACKLIST_IPV4_013: Ipv4Net =
  Ipv4Net::new_assert(Ipv4Addr::new(203, 0, 113, 0), 24);
const FORWARDING_BLACKLIST_IPV4_014: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(240, 0, 0, 0), 4);

const FORWARDING_BLACKLIST_IPV6_001: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  127,
);
const FORWARDING_BLACKLIST_IPV6_002: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0xffff, 0x0000, 0x0000,
  ),
  96,
);
const FORWARDING_BLACKLIST_IPV6_003: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x0100, 0x0000, 0x0000, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  64,
);
const FORWARDING_BLACKLIST_IPV6_004: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  128,
);
const FORWARDING_BLACKLIST_IPV6_005: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0004,
  ),
  126,
);
const FORWARDING_BLACKLIST_IPV6_006: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0008,
  ),
  125,
);
const FORWARDING_BLACKLIST_IPV6_007: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0010,
  ),
  124,
);
const FORWARDING_BLACKLIST_IPV6_008: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0020,
  ),
  123,
);
const FORWARDING_BLACKLIST_IPV6_009: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0040,
  ),
  122,
);
const FORWARDING_BLACKLIST_IPV6_010: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0080,
  ),
  121,
);
const FORWARDING_BLACKLIST_IPV6_011: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0100,
  ),
  120,
);
const FORWARDING_BLACKLIST_IPV6_012: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0200,
  ),
  119,
);
const FORWARDING_BLACKLIST_IPV6_013: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0400,
  ),
  118,
);
const FORWARDING_BLACKLIST_IPV6_014: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0800,
  ),
  117,
);
const FORWARDING_BLACKLIST_IPV6_015: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x1000,
  ),
  116,
);
const FORWARDING_BLACKLIST_IPV6_016: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x2000,
  ),
  115,
);
const FORWARDING_BLACKLIST_IPV6_017: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x4000,
  ),
  114,
);
const FORWARDING_BLACKLIST_IPV6_018: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x8000,
  ),
  113,
);
const FORWARDING_BLACKLIST_IPV6_019: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0001, 0x0000,
  ),
  112,
);
const FORWARDING_BLACKLIST_IPV6_020: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0002, 0x0000,
  ),
  111,
);
const FORWARDING_BLACKLIST_IPV6_021: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0004, 0x0000,
  ),
  110,
);
const FORWARDING_BLACKLIST_IPV6_022: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0008, 0x0000,
  ),
  109,
);
const FORWARDING_BLACKLIST_IPV6_023: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0010, 0x0000,
  ),
  108,
);
const FORWARDING_BLACKLIST_IPV6_024: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0020, 0x0000,
  ),
  107,
);
const FORWARDING_BLACKLIST_IPV6_025: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0040, 0x0000,
  ),
  106,
);
const FORWARDING_BLACKLIST_IPV6_026: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0080, 0x0000,
  ),
  105,
);
const FORWARDING_BLACKLIST_IPV6_027: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0100, 0x0000,
  ),
  104,
);
const FORWARDING_BLACKLIST_IPV6_028: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0200, 0x0000,
  ),
  103,
);
const FORWARDING_BLACKLIST_IPV6_029: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0400, 0x0000,
  ),
  102,
);
const FORWARDING_BLACKLIST_IPV6_030: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0800, 0x0000,
  ),
  101,
);
const FORWARDING_BLACKLIST_IPV6_031: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x1000, 0x0000,
  ),
  100,
);
const FORWARDING_BLACKLIST_IPV6_032: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x2000, 0x0000,
  ),
  99,
);
const FORWARDING_BLACKLIST_IPV6_033: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x4000, 0x0000,
  ),
  98,
);
const FORWARDING_BLACKLIST_IPV6_034: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x8000, 0x0000,
  ),
  97,
);
const FORWARDING_BLACKLIST_IPV6_035: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0001, 0x0000, 0x0000,
  ),
  96,
);
const FORWARDING_BLACKLIST_IPV6_036: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0002, 0x0000, 0x0000,
  ),
  95,
);
const FORWARDING_BLACKLIST_IPV6_037: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0004, 0x0000, 0x0000,
  ),
  94,
);
const FORWARDING_BLACKLIST_IPV6_038: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0008, 0x0000, 0x0000,
  ),
  93,
);
const FORWARDING_BLACKLIST_IPV6_039: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0010, 0x0000, 0x0000,
  ),
  92,
);
const FORWARDING_BLACKLIST_IPV6_040: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0020, 0x0000, 0x0000,
  ),
  91,
);
const FORWARDING_BLACKLIST_IPV6_041: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0040, 0x0000, 0x0000,
  ),
  90,
);
const FORWARDING_BLACKLIST_IPV6_042: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0080, 0x0000, 0x0000,
  ),
  89,
);
const FORWARDING_BLACKLIST_IPV6_043: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0100, 0x0000, 0x0000,
  ),
  88,
);
const FORWARDING_BLACKLIST_IPV6_044: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0200, 0x0000, 0x0000,
  ),
  87,
);
const FORWARDING_BLACKLIST_IPV6_045: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0400, 0x0000, 0x0000,
  ),
  86,
);
const FORWARDING_BLACKLIST_IPV6_046: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0800, 0x0000, 0x0000,
  ),
  85,
);
const FORWARDING_BLACKLIST_IPV6_047: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x1000, 0x0000, 0x0000,
  ),
  84,
);
const FORWARDING_BLACKLIST_IPV6_048: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x2000, 0x0000, 0x0000,
  ),
  83,
);
const FORWARDING_BLACKLIST_IPV6_049: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x4000, 0x0000, 0x0000,
  ),
  82,
);
const FORWARDING_BLACKLIST_IPV6_050: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0000, 0x8000, 0x0000, 0x0000,
  ),
  81,
);
const FORWARDING_BLACKLIST_IPV6_051: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0001, 0x0000, 0x0000, 0x0000,
  ),
  80,
);
const FORWARDING_BLACKLIST_IPV6_052: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0002, 0x0000, 0x0000, 0x0000,
  ),
  79,
);
const FORWARDING_BLACKLIST_IPV6_053: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0004, 0x0000, 0x0000, 0x0000,
  ),
  78,
);
const FORWARDING_BLACKLIST_IPV6_054: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0008, 0x0000, 0x0000, 0x0000,
  ),
  77,
);
const FORWARDING_BLACKLIST_IPV6_055: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0010, 0x0000, 0x0000, 0x0000,
  ),
  76,
);
const FORWARDING_BLACKLIST_IPV6_056: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0020, 0x0000, 0x0000, 0x0000,
  ),
  75,
);
const FORWARDING_BLACKLIST_IPV6_057: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0040, 0x0000, 0x0000, 0x0000,
  ),
  74,
);
const FORWARDING_BLACKLIST_IPV6_058: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0080, 0x0000, 0x0000, 0x0000,
  ),
  73,
);
const FORWARDING_BLACKLIST_IPV6_059: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0100, 0x0000, 0x0000, 0x0000,
  ),
  72,
);
const FORWARDING_BLACKLIST_IPV6_060: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0200, 0x0000, 0x0000, 0x0000,
  ),
  71,
);
const FORWARDING_BLACKLIST_IPV6_061: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0400, 0x0000, 0x0000, 0x0000,
  ),
  70,
);
const FORWARDING_BLACKLIST_IPV6_062: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x0800, 0x0000, 0x0000, 0x0000,
  ),
  69,
);
const FORWARDING_BLACKLIST_IPV6_063: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x1000, 0x0000, 0x0000, 0x0000,
  ),
  68,
);
const FORWARDING_BLACKLIST_IPV6_064: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x2000, 0x0000, 0x0000, 0x0000,
  ),
  67,
);
const FORWARDING_BLACKLIST_IPV6_065: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x4000, 0x0000, 0x0000, 0x0000,
  ),
  66,
);
const FORWARDING_BLACKLIST_IPV6_066: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0000, 0x8000, 0x0000, 0x0000, 0x0000,
  ),
  65,
);
const FORWARDING_BLACKLIST_IPV6_067: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  64,
);
const FORWARDING_BLACKLIST_IPV6_068: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  63,
);
const FORWARDING_BLACKLIST_IPV6_069: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0004, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  62,
);
const FORWARDING_BLACKLIST_IPV6_070: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0008, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  61,
);
const FORWARDING_BLACKLIST_IPV6_071: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0010, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  60,
);
const FORWARDING_BLACKLIST_IPV6_072: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0020, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  59,
);
const FORWARDING_BLACKLIST_IPV6_073: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0040, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  58,
);
const FORWARDING_BLACKLIST_IPV6_074: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0080, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  57,
);
const FORWARDING_BLACKLIST_IPV6_075: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0100, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  56,
);
const FORWARDING_BLACKLIST_IPV6_076: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0200, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  55,
);
const FORWARDING_BLACKLIST_IPV6_077: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0400, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  54,
);
const FORWARDING_BLACKLIST_IPV6_078: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x0800, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  53,
);
const FORWARDING_BLACKLIST_IPV6_079: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x1000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  52,
);
const FORWARDING_BLACKLIST_IPV6_080: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x2000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  51,
);
const FORWARDING_BLACKLIST_IPV6_081: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x4000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  50,
);
const FORWARDING_BLACKLIST_IPV6_082: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0000, 0x8000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  49,
);
const FORWARDING_BLACKLIST_IPV6_083: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  48,
);
const FORWARDING_BLACKLIST_IPV6_084: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  47,
);
const FORWARDING_BLACKLIST_IPV6_085: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0004, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  46,
);
const FORWARDING_BLACKLIST_IPV6_086: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0008, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  45,
);
const FORWARDING_BLACKLIST_IPV6_087: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0010, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  44,
);
const FORWARDING_BLACKLIST_IPV6_088: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0020, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  43,
);
const FORWARDING_BLACKLIST_IPV6_089: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0040, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  42,
);
const FORWARDING_BLACKLIST_IPV6_090: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0080, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  41,
);
const FORWARDING_BLACKLIST_IPV6_091: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0100, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  40,
);
const FORWARDING_BLACKLIST_IPV6_092: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0200, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  39,
);
const FORWARDING_BLACKLIST_IPV6_093: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0400, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  38,
);
const FORWARDING_BLACKLIST_IPV6_094: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x0800, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  37,
);
const FORWARDING_BLACKLIST_IPV6_095: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x1000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  36,
);
const FORWARDING_BLACKLIST_IPV6_096: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x2000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  35,
);
const FORWARDING_BLACKLIST_IPV6_097: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x4000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  34,
);
const FORWARDING_BLACKLIST_IPV6_098: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0001, 0x8000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  33,
);
const FORWARDING_BLACKLIST_IPV6_099: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0002, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  48,
);
const FORWARDING_BLACKLIST_IPV6_100: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0002, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  47,
);
const FORWARDING_BLACKLIST_IPV6_101: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0002, 0x0004, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  46,
);
const FORWARDING_BLACKLIST_IPV6_102: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0002, 0x0008, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  45,
);
const FORWARDING_BLACKLIST_IPV6_103: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0002, 0x0010, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  44,
);
const FORWARDING_BLACKLIST_IPV6_104: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0002, 0x0020, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  43,
);
const FORWARDING_BLACKLIST_IPV6_105: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0002, 0x0040, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  42,
);
const FORWARDING_BLACKLIST_IPV6_106: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0002, 0x0080, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  41,
);
const FORWARDING_BLACKLIST_IPV6_107: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0002, 0x0100, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  40,
);
const FORWARDING_BLACKLIST_IPV6_108: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0002, 0x0200, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  39,
);
const FORWARDING_BLACKLIST_IPV6_109: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0002, 0x0400, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  38,
);
const FORWARDING_BLACKLIST_IPV6_110: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0002, 0x0800, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  37,
);
const FORWARDING_BLACKLIST_IPV6_111: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0002, 0x1000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  36,
);
const FORWARDING_BLACKLIST_IPV6_112: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0002, 0x2000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  35,
);
const FORWARDING_BLACKLIST_IPV6_113: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0002, 0x4000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  34,
);
const FORWARDING_BLACKLIST_IPV6_114: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0002, 0x8000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  33,
);
const FORWARDING_BLACKLIST_IPV6_115: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0004, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  40,
);
const FORWARDING_BLACKLIST_IPV6_116: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0004, 0x0100, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  44,
);
const FORWARDING_BLACKLIST_IPV6_117: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0004, 0x0110, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  47,
);
const FORWARDING_BLACKLIST_IPV6_118: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0004, 0x0113, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  48,
);
const FORWARDING_BLACKLIST_IPV6_119: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0004, 0x0114, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  46,
);
const FORWARDING_BLACKLIST_IPV6_120: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0004, 0x0118, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  45,
);
const FORWARDING_BLACKLIST_IPV6_121: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0004, 0x0120, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  43,
);
const FORWARDING_BLACKLIST_IPV6_122: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0004, 0x0140, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  42,
);
const FORWARDING_BLACKLIST_IPV6_123: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0004, 0x0180, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  41,
);
const FORWARDING_BLACKLIST_IPV6_124: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0004, 0x0200, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  39,
);
const FORWARDING_BLACKLIST_IPV6_125: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0004, 0x0400, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  38,
);
const FORWARDING_BLACKLIST_IPV6_126: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0004, 0x0800, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  37,
);
const FORWARDING_BLACKLIST_IPV6_127: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0004, 0x1000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  36,
);
const FORWARDING_BLACKLIST_IPV6_128: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0004, 0x2000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  35,
);
const FORWARDING_BLACKLIST_IPV6_129: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0004, 0x4000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  34,
);
const FORWARDING_BLACKLIST_IPV6_130: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0004, 0x8000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  33,
);
const FORWARDING_BLACKLIST_IPV6_131: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0005, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  32,
);
const FORWARDING_BLACKLIST_IPV6_132: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0006, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  31,
);
const FORWARDING_BLACKLIST_IPV6_133: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0008, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  29,
);
const FORWARDING_BLACKLIST_IPV6_134: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0040, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  26,
);
const FORWARDING_BLACKLIST_IPV6_135: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0080, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  25,
);
const FORWARDING_BLACKLIST_IPV6_136: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0100, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  24,
);
const FORWARDING_BLACKLIST_IPV6_137: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x2001, 0x0db8, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  32,
);
const FORWARDING_BLACKLIST_IPV6_138: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0x3fff, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  20,
);
const FORWARDING_BLACKLIST_IPV6_139: Ipv6Net = Ipv6Net::new_assert(
  Ipv6Addr::new(
    0xfe80, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ),
  10,
);

pub(super) const RFC6890_IPV4_NETS: &[Ipv4Net] = &[
  RFC6890_IPV4_001,
  RFC6890_IPV4_002,
  RFC6890_IPV4_003,
  RFC6890_IPV4_004,
  RFC6890_IPV4_005,
  RFC6890_IPV4_006,
  RFC6890_IPV4_007,
  RFC6890_IPV4_008,
  RFC6890_IPV4_009,
  RFC6890_IPV4_010,
  RFC6890_IPV4_011,
  RFC6890_IPV4_012,
  RFC6890_IPV4_013,
  RFC6890_IPV4_014,
  RFC6890_IPV4_015,
  RFC6890_IPV4_016,
  RFC6890_IPV4_017,
  RFC6890_IPV4_018,
  RFC6890_IPV4_019,
  RFC6890_IPV4_020,
  RFC6890_IPV4_021,
  RFC6890_IPV4_022,
  RFC6890_IPV4_023,
  RFC6890_IPV4_024,
  RFC6890_IPV4_025,
  RFC6890_IPV4_026,
];

pub(super) const RFC6890_IPV6_NETS: &[Ipv6Net] = &[
  RFC6890_IPV6_001,
  RFC6890_IPV6_002,
  RFC6890_IPV6_003,
  RFC6890_IPV6_004,
  RFC6890_IPV6_005,
  RFC6890_IPV6_006,
  RFC6890_IPV6_007,
  RFC6890_IPV6_008,
  RFC6890_IPV6_009,
  RFC6890_IPV6_010,
  RFC6890_IPV6_011,
  RFC6890_IPV6_012,
  RFC6890_IPV6_013,
  RFC6890_IPV6_014,
  RFC6890_IPV6_015,
  RFC6890_IPV6_016,
  RFC6890_IPV6_017,
  RFC6890_IPV6_018,
  RFC6890_IPV6_019,
  RFC6890_IPV6_020,
  RFC6890_IPV6_021,
  RFC6890_IPV6_022,
  RFC6890_IPV6_023,
  RFC6890_IPV6_024,
  RFC6890_IPV6_025,
];

pub(super) const RFC6890_IP_NETS: &[IpNet] = &[
  IpNet::V4(RFC6890_IPV4_001),
  IpNet::V4(RFC6890_IPV4_002),
  IpNet::V4(RFC6890_IPV4_003),
  IpNet::V4(RFC6890_IPV4_004),
  IpNet::V4(RFC6890_IPV4_005),
  IpNet::V4(RFC6890_IPV4_006),
  IpNet::V4(RFC6890_IPV4_007),
  IpNet::V4(RFC6890_IPV4_008),
  IpNet::V4(RFC6890_IPV4_009),
  IpNet::V4(RFC6890_IPV4_010),
  IpNet::V4(RFC6890_IPV4_011),
  IpNet::V4(RFC6890_IPV4_012),
  IpNet::V4(RFC6890_IPV4_013),
  IpNet::V4(RFC6890_IPV4_014),
  IpNet::V4(RFC6890_IPV4_015),
  IpNet::V4(RFC6890_IPV4_016),
  IpNet::V4(RFC6890_IPV4_017),
  IpNet::V4(RFC6890_IPV4_018),
  IpNet::V4(RFC6890_IPV4_019),
  IpNet::V4(RFC6890_IPV4_020),
  IpNet::V4(RFC6890_IPV4_021),
  IpNet::V4(RFC6890_IPV4_022),
  IpNet::V4(RFC6890_IPV4_023),
  IpNet::V4(RFC6890_IPV4_024),
  IpNet::V4(RFC6890_IPV4_025),
  IpNet::V4(RFC6890_IPV4_026),
  IpNet::V6(RFC6890_IPV6_001),
  IpNet::V6(RFC6890_IPV6_002),
  IpNet::V6(RFC6890_IPV6_003),
  IpNet::V6(RFC6890_IPV6_004),
  IpNet::V6(RFC6890_IPV6_005),
  IpNet::V6(RFC6890_IPV6_006),
  IpNet::V6(RFC6890_IPV6_007),
  IpNet::V6(RFC6890_IPV6_008),
  IpNet::V6(RFC6890_IPV6_009),
  IpNet::V6(RFC6890_IPV6_010),
  IpNet::V6(RFC6890_IPV6_011),
  IpNet::V6(RFC6890_IPV6_012),
  IpNet::V6(RFC6890_IPV6_013),
  IpNet::V6(RFC6890_IPV6_014),
  IpNet::V6(RFC6890_IPV6_015),
  IpNet::V6(RFC6890_IPV6_016),
  IpNet::V6(RFC6890_IPV6_017),
  IpNet::V6(RFC6890_IPV6_018),
  IpNet::V6(RFC6890_IPV6_019),
  IpNet::V6(RFC6890_IPV6_020),
  IpNet::V6(RFC6890_IPV6_021),
  IpNet::V6(RFC6890_IPV6_022),
  IpNet::V6(RFC6890_IPV6_023),
  IpNet::V6(RFC6890_IPV6_024),
  IpNet::V6(RFC6890_IPV6_025),
];

pub(super) const FORWARDING_BLACKLIST_IPV4_NETS: &[Ipv4Net] = &[
  FORWARDING_BLACKLIST_IPV4_001,
  FORWARDING_BLACKLIST_IPV4_002,
  FORWARDING_BLACKLIST_IPV4_003,
  FORWARDING_BLACKLIST_IPV4_004,
  FORWARDING_BLACKLIST_IPV4_005,
  FORWARDING_BLACKLIST_IPV4_006,
  FORWARDING_BLACKLIST_IPV4_007,
  FORWARDING_BLACKLIST_IPV4_008,
  FORWARDING_BLACKLIST_IPV4_009,
  FORWARDING_BLACKLIST_IPV4_010,
  FORWARDING_BLACKLIST_IPV4_011,
  FORWARDING_BLACKLIST_IPV4_012,
  FORWARDING_BLACKLIST_IPV4_013,
  FORWARDING_BLACKLIST_IPV4_014,
];

pub(super) const FORWARDING_BLACKLIST_IPV6_NETS: &[Ipv6Net] = &[
  FORWARDING_BLACKLIST_IPV6_001,
  FORWARDING_BLACKLIST_IPV6_002,
  FORWARDING_BLACKLIST_IPV6_003,
  FORWARDING_BLACKLIST_IPV6_004,
  FORWARDING_BLACKLIST_IPV6_005,
  FORWARDING_BLACKLIST_IPV6_006,
  FORWARDING_BLACKLIST_IPV6_007,
  FORWARDING_BLACKLIST_IPV6_008,
  FORWARDING_BLACKLIST_IPV6_009,
  FORWARDING_BLACKLIST_IPV6_010,
  FORWARDING_BLACKLIST_IPV6_011,
  FORWARDING_BLACKLIST_IPV6_012,
  FORWARDING_BLACKLIST_IPV6_013,
  FORWARDING_BLACKLIST_IPV6_014,
  FORWARDING_BLACKLIST_IPV6_015,
  FORWARDING_BLACKLIST_IPV6_016,
  FORWARDING_BLACKLIST_IPV6_017,
  FORWARDING_BLACKLIST_IPV6_018,
  FORWARDING_BLACKLIST_IPV6_019,
  FORWARDING_BLACKLIST_IPV6_020,
  FORWARDING_BLACKLIST_IPV6_021,
  FORWARDING_BLACKLIST_IPV6_022,
  FORWARDING_BLACKLIST_IPV6_023,
  FORWARDING_BLACKLIST_IPV6_024,
  FORWARDING_BLACKLIST_IPV6_025,
  FORWARDING_BLACKLIST_IPV6_026,
  FORWARDING_BLACKLIST_IPV6_027,
  FORWARDING_BLACKLIST_IPV6_028,
  FORWARDING_BLACKLIST_IPV6_029,
  FORWARDING_BLACKLIST_IPV6_030,
  FORWARDING_BLACKLIST_IPV6_031,
  FORWARDING_BLACKLIST_IPV6_032,
  FORWARDING_BLACKLIST_IPV6_033,
  FORWARDING_BLACKLIST_IPV6_034,
  FORWARDING_BLACKLIST_IPV6_035,
  FORWARDING_BLACKLIST_IPV6_036,
  FORWARDING_BLACKLIST_IPV6_037,
  FORWARDING_BLACKLIST_IPV6_038,
  FORWARDING_BLACKLIST_IPV6_039,
  FORWARDING_BLACKLIST_IPV6_040,
  FORWARDING_BLACKLIST_IPV6_041,
  FORWARDING_BLACKLIST_IPV6_042,
  FORWARDING_BLACKLIST_IPV6_043,
  FORWARDING_BLACKLIST_IPV6_044,
  FORWARDING_BLACKLIST_IPV6_045,
  FORWARDING_BLACKLIST_IPV6_046,
  FORWARDING_BLACKLIST_IPV6_047,
  FORWARDING_BLACKLIST_IPV6_048,
  FORWARDING_BLACKLIST_IPV6_049,
  FORWARDING_BLACKLIST_IPV6_050,
  FORWARDING_BLACKLIST_IPV6_051,
  FORWARDING_BLACKLIST_IPV6_052,
  FORWARDING_BLACKLIST_IPV6_053,
  FORWARDING_BLACKLIST_IPV6_054,
  FORWARDING_BLACKLIST_IPV6_055,
  FORWARDING_BLACKLIST_IPV6_056,
  FORWARDING_BLACKLIST_IPV6_057,
  FORWARDING_BLACKLIST_IPV6_058,
  FORWARDING_BLACKLIST_IPV6_059,
  FORWARDING_BLACKLIST_IPV6_060,
  FORWARDING_BLACKLIST_IPV6_061,
  FORWARDING_BLACKLIST_IPV6_062,
  FORWARDING_BLACKLIST_IPV6_063,
  FORWARDING_BLACKLIST_IPV6_064,
  FORWARDING_BLACKLIST_IPV6_065,
  FORWARDING_BLACKLIST_IPV6_066,
  FORWARDING_BLACKLIST_IPV6_067,
  FORWARDING_BLACKLIST_IPV6_068,
  FORWARDING_BLACKLIST_IPV6_069,
  FORWARDING_BLACKLIST_IPV6_070,
  FORWARDING_BLACKLIST_IPV6_071,
  FORWARDING_BLACKLIST_IPV6_072,
  FORWARDING_BLACKLIST_IPV6_073,
  FORWARDING_BLACKLIST_IPV6_074,
  FORWARDING_BLACKLIST_IPV6_075,
  FORWARDING_BLACKLIST_IPV6_076,
  FORWARDING_BLACKLIST_IPV6_077,
  FORWARDING_BLACKLIST_IPV6_078,
  FORWARDING_BLACKLIST_IPV6_079,
  FORWARDING_BLACKLIST_IPV6_080,
  FORWARDING_BLACKLIST_IPV6_081,
  FORWARDING_BLACKLIST_IPV6_082,
  FORWARDING_BLACKLIST_IPV6_083,
  FORWARDING_BLACKLIST_IPV6_084,
  FORWARDING_BLACKLIST_IPV6_085,
  FORWARDING_BLACKLIST_IPV6_086,
  FORWARDING_BLACKLIST_IPV6_087,
  FORWARDING_BLACKLIST_IPV6_088,
  FORWARDING_BLACKLIST_IPV6_089,
  FORWARDING_BLACKLIST_IPV6_090,
  FORWARDING_BLACKLIST_IPV6_091,
  FORWARDING_BLACKLIST_IPV6_092,
  FORWARDING_BLACKLIST_IPV6_093,
  FORWARDING_BLACKLIST_IPV6_094,
  FORWARDING_BLACKLIST_IPV6_095,
  FORWARDING_BLACKLIST_IPV6_096,
  FORWARDING_BLACKLIST_IPV6_097,
  FORWARDING_BLACKLIST_IPV6_098,
  FORWARDING_BLACKLIST_IPV6_099,
  FORWARDING_BLACKLIST_IPV6_100,
  FORWARDING_BLACKLIST_IPV6_101,
  FORWARDING_BLACKLIST_IPV6_102,
  FORWARDING_BLACKLIST_IPV6_103,
  FORWARDING_BLACKLIST_IPV6_104,
  FORWARDING_BLACKLIST_IPV6_105,
  FORWARDING_BLACKLIST_IPV6_106,
  FORWARDING_BLACKLIST_IPV6_107,
  FORWARDING_BLACKLIST_IPV6_108,
  FORWARDING_BLACKLIST_IPV6_109,
  FORWARDING_BLACKLIST_IPV6_110,
  FORWARDING_BLACKLIST_IPV6_111,
  FORWARDING_BLACKLIST_IPV6_112,
  FORWARDING_BLACKLIST_IPV6_113,
  FORWARDING_BLACKLIST_IPV6_114,
  FORWARDING_BLACKLIST_IPV6_115,
  FORWARDING_BLACKLIST_IPV6_116,
  FORWARDING_BLACKLIST_IPV6_117,
  FORWARDING_BLACKLIST_IPV6_118,
  FORWARDING_BLACKLIST_IPV6_119,
  FORWARDING_BLACKLIST_IPV6_120,
  FORWARDING_BLACKLIST_IPV6_121,
  FORWARDING_BLACKLIST_IPV6_122,
  FORWARDING_BLACKLIST_IPV6_123,
  FORWARDING_BLACKLIST_IPV6_124,
  FORWARDING_BLACKLIST_IPV6_125,
  FORWARDING_BLACKLIST_IPV6_126,
  FORWARDING_BLACKLIST_IPV6_127,
  FORWARDING_BLACKLIST_IPV6_128,
  FORWARDING_BLACKLIST_IPV6_129,
  FORWARDING_BLACKLIST_IPV6_130,
  FORWARDING_BLACKLIST_IPV6_131,
  FORWARDING_BLACKLIST_IPV6_132,
  FORWARDING_BLACKLIST_IPV6_133,
  FORWARDING_BLACKLIST_IPV6_134,
  FORWARDING_BLACKLIST_IPV6_135,
  FORWARDING_BLACKLIST_IPV6_136,
  FORWARDING_BLACKLIST_IPV6_137,
  FORWARDING_BLACKLIST_IPV6_138,
  FORWARDING_BLACKLIST_IPV6_139,
];

pub(super) const FORWARDING_BLACKLIST_IP_NETS: &[IpNet] = &[
  IpNet::V4(FORWARDING_BLACKLIST_IPV4_001),
  IpNet::V4(FORWARDING_BLACKLIST_IPV4_002),
  IpNet::V4(FORWARDING_BLACKLIST_IPV4_003),
  IpNet::V4(FORWARDING_BLACKLIST_IPV4_004),
  IpNet::V4(FORWARDING_BLACKLIST_IPV4_005),
  IpNet::V4(FORWARDING_BLACKLIST_IPV4_006),
  IpNet::V4(FORWARDING_BLACKLIST_IPV4_007),
  IpNet::V4(FORWARDING_BLACKLIST_IPV4_008),
  IpNet::V4(FORWARDING_BLACKLIST_IPV4_009),
  IpNet::V4(FORWARDING_BLACKLIST_IPV4_010),
  IpNet::V4(FORWARDING_BLACKLIST_IPV4_011),
  IpNet::V4(FORWARDING_BLACKLIST_IPV4_012),
  IpNet::V4(FORWARDING_BLACKLIST_IPV4_013),
  IpNet::V4(FORWARDING_BLACKLIST_IPV4_014),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_001),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_002),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_003),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_004),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_005),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_006),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_007),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_008),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_009),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_010),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_011),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_012),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_013),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_014),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_015),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_016),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_017),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_018),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_019),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_020),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_021),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_022),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_023),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_024),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_025),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_026),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_027),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_028),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_029),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_030),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_031),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_032),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_033),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_034),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_035),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_036),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_037),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_038),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_039),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_040),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_041),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_042),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_043),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_044),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_045),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_046),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_047),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_048),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_049),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_050),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_051),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_052),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_053),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_054),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_055),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_056),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_057),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_058),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_059),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_060),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_061),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_062),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_063),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_064),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_065),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_066),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_067),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_068),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_069),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_070),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_071),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_072),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_073),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_074),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_075),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_076),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_077),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_078),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_079),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_080),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_081),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_082),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_083),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_084),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_085),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_086),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_087),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_088),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_089),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_090),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_091),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_092),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_093),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_094),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_095),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_096),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_097),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_098),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_099),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_100),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_101),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_102),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_103),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_104),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_105),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_106),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_107),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_108),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_109),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_110),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_111),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_112),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_113),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_114),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_115),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_116),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_117),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_118),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_119),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_120),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_121),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_122),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_123),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_124),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_125),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_126),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_127),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_128),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_129),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_130),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_131),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_132),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_133),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_134),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_135),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_136),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_137),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_138),
  IpNet::V6(FORWARDING_BLACKLIST_IPV6_139),
];
