name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'COPYRIGHT'
      - 'LICENSE-*'
      - '**.txt'
  pull_request:
    paths-ignore:
      - 'COPYRIGHT'
      - 'LICENSE-*'
      - '**.txt'
  workflow_dispatch:
  schedule: 
    - cron: "0 1 1 * *"

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1
  nightly: nightly
  stable: stable

jobs:
  # Check formatting
  rustfmt:
    name: rustfmt
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v7
    - name: Install Rust
      # --no-self-update is necessary because the windows environment cannot self-update rustup.exe.
      run: rustup update stable --no-self-update && rustup default stable
    - name: Check formatting
      run: cargo fmt --all -- --check


  # Apply clippy lints
  clippy:
    name: clippy
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v7
    - name: Install Rust
      # --no-self-update is necessary because the windows environment cannot self-update rustup.exe.
      run: rustup update stable --no-self-update && rustup default stable
    - name: Install cargo-hack
      run: cargo install cargo-hack
    - name: Apply clippy lints
      run: cargo clippy --all-targets --all-features -- -D warnings

  build:
    name: build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v7
    - name: Cache cargo build and registry
      uses: actions/cache@v6
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-
    - name: Install Rust
      # --no-self-update is necessary because the windows environment cannot self-update rustup.exe.
      run: rustup update stable --no-self-update && rustup default stable
    - name: Install cargo-hack
      run: cargo install cargo-hack
    - name: Cache ~/.cargo
      uses: actions/cache@v6
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-coverage-dotcargo
    - name: Run build
      run: cargo build
  
  test:
    name: test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v7
    - name: Cache cargo build and registry
      uses: actions/cache@v6
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-test-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-test-
    - name: Install Rust
      # --no-self-update is necessary because the windows environment cannot self-update rustup.exe.
      run: rustup update stable --no-self-update && rustup default stable
    - name: Install cargo-hack
      run: cargo install cargo-hack
    - name: Cache ~/.cargo
      uses: actions/cache@v6
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-coverage-dotcargo
    - name: Run test
      run: cargo test

  compatibility:
    name: compatibility
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Install stable Rust
      run: rustup update stable --no-self-update && rustup default stable
    - name: Test stable feature combinations
      run: |
        cargo +stable test
        cargo +stable test --no-default-features
        cargo +stable test --no-default-features --features serde
        cargo +stable test --all-features
    - name: Install Rust 1.81
      run: rustup toolchain install 1.81.0 --profile minimal
    - name: Check Rust 1.81 all features
      run: cargo +1.81.0 check --all-features
    - name: Test Rust 1.81 all features
      run: cargo +1.81.0 test --all-features --lib
    - name: Doctest Rust 1.81 all features
      run: cargo +1.81.0 test --all-features --doc
    - name: Add bare-metal target
      run: rustup target add thumbv7em-none-eabihf --toolchain stable
    - name: Check bare-metal feature combinations
      run: |
        cargo +stable check --target thumbv7em-none-eabihf --no-default-features
        cargo +stable check --target thumbv7em-none-eabihf --no-default-features --features serde

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    needs:
      - rustfmt
      - clippy
      - build
      - test
      - compatibility
    steps:
      - uses: actions/checkout@v7
      - name: Install latest nightly
        run: rustup toolchain install nightly --profile minimal
      - name: Install cargo-tarpaulin
        run: cargo +nightly install cargo-tarpaulin --locked
      - name: Cache ~/.cargo
        uses: actions/cache@v6
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-coverage-dotcargo
      - name: Cache cargo build
        uses: actions/cache@v6
        with:
          path: target
          key: ${{ runner.os }}-coverage-cargo-build-target
      - name: Run tarpaulin
        run: cargo +nightly tarpaulin --engine llvm --all-features --run-types lib --run-types tests --run-types doctests --workspace --out xml
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}
          fail_ci_if_error: true
